### ISSUE TITLE
exec user process caused "exec format error"

### ISSUE THREAD

**Issue by notslang** [certbot/certbot-docker#1]
I'm trying to run certbot on a Raspberry Pi 3 B+, but I get the error `standard_init_linux.go:211: exec user process caused "exec format error"`.

```
[slang@alarmpi ~]$ docker pull certbot/certbot
Using default tag: latest
latest: Pulling from certbot/certbot
050382585609: Pull complete
39e8b6a82737: Pull complete
9c3480ede676: Pull complete
7dbf571e3a56: Pull complete
9bb6018c38b6: Pull complete
eb34e770aadb: Pull complete
48b3917fa816: Pull complete
1807b38b6e0c: Pull complete
8c132af6b00c: Pull complete
Digest: sha256:f92b35d7b247190648149d8583ed143c061827ceac6775c30f5cd03b03319826
Status: Downloaded newer image for certbot/certbot:latest
docker.io/certbot/certbot:latest
[slang@alarmpi ~]$ docker run --rm  certbot/certbot --help
standard_init_linux.go:211: exec user process caused "exec format error"
```

Running the same 2 commands on my non-ARM laptop works as expected; it prints out the help text.

**Comment by bmw** [comment]
Ggoogling around, it looks like this error is caused by the image being x86 specific rather than ARM. See issues like https://github.com/docker-library/mysql/issues/228.

I'm honestly not very familiar with this. Is there a way for us to configure our automated builds on Docker Hub to builds for different architectures?

**Comment by SquallHalle** [comment]
just use: 
certbot:
    image: certbot/certbot:arm32v6-latest
:-)

**Comment by bmw** [comment]
I think this issue is resolved with #3.

**Comment by MiChAeLoKGB** [comment]
Seems like the issue is still not resolved

```Shell
pi@raspberrypi:~/docker $ docker run -it certbot/certbot arbitrary-command
standard_init_linux.go:211: exec user process caused "exec format error"
failed to resize tty, using default size
```
When I used `certbot/certbot:arm32v6-latest` it worked fine.

**Comment by bmw** [comment]
That is expected behavior because we chose not to add a manifest since it is an experimental feature at https://github.com/certbot-docker/certbot-docker/pull/3.

If you would like us to reconsider, please open a new issue/PR.
